repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: detect-private-key
  - id: forbid-new-submodules
  # - id: no-commit-to-branch
  #   args: ['--branch', 'master']
- repo: https://github.com/Yelp/detect-secrets # git@github.com:Yelp/detect-secrets
  rev: v0.13.1
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']